#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:53.
#
# Description: Give items from table row #13
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:items/names/hypergay_axe_of_engima
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:items/names/hypergay_lumberjack_axe
execute if score #number_of_names minuncraft matches 3.. run function minuncraft:items/names/hypergay_axe_of_kaitlin
execute if score #number_of_names minuncraft matches 4.. run function minuncraft:items/names/hypergay_axe
