#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:53.
#
# Description: Give items from table row #22
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:items/names/transrite_axe
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:items/names/trans_rights_axe
execute if score #number_of_names minuncraft matches 3.. run function minuncraft:items/names/axe_says_trans_rights
execute if score #number_of_names minuncraft matches 4.. run function minuncraft:items/names/this_axe_says_trans_rights
