#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:54.
#
# Description: Give items from table row #276
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:items/names/zombie_pigblade
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:items/names/zombie_pigsword
execute if score #number_of_names minuncraft matches 3.. run function minuncraft:items/names/zombie_pigman_sword
execute if score #number_of_names minuncraft matches 4.. run function minuncraft:items/names/zistonian_sword
execute if score #number_of_names minuncraft matches 5.. run function minuncraft:items/names/piglin_sword
