#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:55.
#
# Description: Give items from table row #449
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:items/names/ylissean_falchion
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:items/names/sealed_falchion
execute if score #number_of_names minuncraft matches 3.. run function minuncraft:items/names/parallel_falchion
execute if score #number_of_names minuncraft matches 4.. run function minuncraft:items/names/exalted_falchion
execute if score #number_of_names minuncraft matches 5.. run function minuncraft:items/names/awakening_falchion
