#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:55.
#
# Description: Give items from table row #701
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:items/names/docked_purple-orange_nintendo_switch
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:items/names/docked_purple-orange_switch
execute if score #number_of_names minuncraft matches 3.. run function minuncraft:items/names/docked_neon_purple_and_neon_orange_switch
execute if score #number_of_names minuncraft matches 4.. run function minuncraft:items/names/docked_neon_purple_and_neon_orange_nintendo_switch
