#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:54.
#
# Description: Give items with name Acacia Wood Bow
# Called by:	 Player
# Entity @s:	 Player
#
give @s bow{display:{Name:'{"text":"Acacia Wood Bow"}'}}
