#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:55.
#
# Description: Give items with name Antlion Digging Claws
# Called by:	 Player
# Entity @s:	 Player
#
execute if data storage minuncraft:settings base_item{"stone":"Enabled"} run give @s stone_shovel{display:{Name:'{"text":"Antlion Digging Claws"}'}}
execute if data storage minuncraft:settings base_item{"iron":"Enabled"} run give @s iron_shovel{display:{Name:'{"text":"Antlion Digging Claws"}'}}
execute if data storage minuncraft:settings base_item{"diamond":"Enabled"} run give @s diamond_shovel{display:{Name:'{"text":"Antlion Digging Claws"}'}}
execute if data storage minuncraft:settings base_item{"netherite":"Enabled"} run give @s netherite_shovel{display:{Name:'{"text":"Antlion Digging Claws"}'}}
execute if data storage minuncraft:settings base_item{"stone":"Enabled"} run give @s stone_sword{display:{Name:'{"text":"Antlion Digging Claws"}'}}
execute if data storage minuncraft:settings base_item{"iron":"Enabled"} run give @s iron_sword{display:{Name:'{"text":"Antlion Digging Claws"}'}}
execute if data storage minuncraft:settings base_item{"diamond":"Enabled"} run give @s diamond_sword{display:{Name:'{"text":"Antlion Digging Claws"}'}}
execute if data storage minuncraft:settings base_item{"netherite":"Enabled"} run give @s netherite_sword{display:{Name:'{"text":"Antlion Digging Claws"}'}}
