#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:56.
#
# Description: Give items with name Axolotl of Undying
# Called by:	 Player
# Entity @s:	 Player
#
give @s totem_of_undying{display:{Name:'{"text":"Axolotl of Undying"}'}}
