#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:54.
#
# Description: Give items with name Banana Axe
# Called by:	 Player
# Entity @s:	 Player
#
give @s banana_axe{display:{Name:'{"text":"Banana Axe"}'}}
