#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:55.
#
# Description: Give items with name Curry Rice
# Called by:	 Player
# Entity @s:	 Player
#
give @s rabbit_stew{display:{Name:'{"text":"Curry Rice"}'}}
give @s mushroom_stew{display:{Name:'{"text":"Curry Rice"}'}}
give @s beetroot_soup{display:{Name:'{"text":"Curry Rice"}'}}
