#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:55.
#
# Description: Give items with name Docked Neon Red and Neon Blue Switch
# Called by:	 Player
# Entity @s:	 Player
#
execute if data storage minuncraft:settings base_item{"iron":"Enabled"} run give @s iron_ingot{display:{Name:'{"text":"Docked Neon Red and Neon Blue Switch"}'}}
