#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:56.
#
# Description: Give items with name Foul Soap
# Called by:	 Player
# Entity @s:	 Player
#
give @s poisonous_potato{display:{Name:'{"text":"Foul Soap"}'}}
give @s honeycomb{display:{Name:'{"text":"Foul Soap"}'}}
