#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:54.
#
# Description: Give items with name Fried Egg
# Called by:	 Player
# Entity @s:	 Player
#
give @s baked_potato{display:{Name:'{"text":"Fried Egg"}'}}
give @s potato{display:{Name:'{"text":"Fried Egg"}'}}
give @s bread{display:{Name:'{"text":"Fried Egg"}'}}
