#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:55.
#
# Description: Give items with name Golden Turnip
# Called by:	 Player
# Entity @s:	 Player
#
execute if data storage minuncraft:settings base_item{"gold":"Enabled"} run give @s golden_carrot{display:{Name:'{"text":"Golden Turnip"}'}}
execute if data storage minuncraft:settings base_item{"gold":"Enabled"} run give @s gold_ingot{display:{Name:'{"text":"Golden Turnip"}'}}
