#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:55.
#
# Description: Give items with name Heart Piece
# Called by:	 Player
# Entity @s:	 Player
#
give @s red_dye{display:{Name:'{"text":"Heart Piece"}'}}
give @s redstone_dust{display:{Name:'{"text":"Heart Piece"}'}}
give @s emerald{display:{Name:'{"text":"Heart Piece"}'}}
