#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:53.
#
# Description: Give items with name Hypergay Star Hitter
# Called by:	 Player
# Entity @s:	 Player
#
give @s bow{display:{Name:'{"text":"Hypergay Star Hitter"}'}}
