#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:55.
#
# Description: Give items with name I Want to be a Cute Anime Girl
# Called by:	 Player
# Entity @s:	 Player
#
give @s book{display:{Name:'{"text":"I Want to be a Cute Anime Girl"}'}}
