#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:54.
#
# Description: Give items with name Iron Lucerne Hammer
# Called by:	 Player
# Entity @s:	 Player
#
execute if data storage minuncraft:settings base_item{"iron":"Enabled"} run give @s iron_axe{display:{Name:'{"text":"Iron Lucerne Hammer"}'}}
execute if data storage minuncraft:settings base_item{"iron":"Enabled"} run give @s iron_sword{display:{Name:'{"text":"Iron Lucerne Hammer"}'}}
