#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:56.
#
# Description: Give items with name Leather Wolf Armour
# Called by:	 Player
# Entity @s:	 Player
#
execute if data storage minuncraft:settings base_item{"leather":"Enabled"} run give @s leather{display:{Name:'{"text":"Leather Wolf Armour"}'}}
