#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:56.
#
# Description: Give items with name Light Grey Pencil
# Called by:	 Player
# Entity @s:	 Player
#
give @s stick{display:{Name:'{"text":"Light Grey Pencil"}'}}
