#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:55.
#
# Description: Give items with name Marco Dimensional Scissors
# Called by:	 Player
# Entity @s:	 Player
#
give @s shears{display:{Name:'{"text":"Marco Dimensional Scissors"}'}}
