#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:54.
#
# Description: Give items with name Mint Ice Cream
# Called by:	 Player
# Entity @s:	 Player
#
give @s beetroot_soup{display:{Name:'{"text":"Mint Ice Cream"}'}}
give @s mushroom_stew{display:{Name:'{"text":"Mint Ice Cream"}'}}
