#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:56.
#
# Description: Give items with name Needle and String
# Called by:	 Player
# Entity @s:	 Player
#
give @s stick{display:{Name:'{"text":"Needle and String"}'}}
give @s string{display:{Name:'{"text":"Needle and String"}'}}
