#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:54.
#
# Description: Give items with name Oak Wood Shovel
# Called by:	 Player
# Entity @s:	 Player
#
execute if data storage minuncraft:settings base_item{"wood":"Enabled"} run give @s wooden_shovel{display:{Name:'{"text":"Oak Wood Shovel"}'}}
