#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:54.
#
# Description: Give items with name Pawpaw
# Called by:	 Player
# Entity @s:	 Player
#
give @s apple{display:{Name:'{"text":"Pawpaw"}'}}
give @s melon_slice{display:{Name:'{"text":"Pawpaw"}'}}
