#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:54.
#
# Description: Give items with name Red Chili
# Called by:	 Player
# Entity @s:	 Player
#
give @s apple{display:{Name:'{"text":"Red Chili"}'}}
give @s beetroot{display:{Name:'{"text":"Red Chili"}'}}
give @s carrot{display:{Name:'{"text":"Red Chili"}'}}
