#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:54.
#
# Description: Give items with name Ruby Gem
# Called by:	 Player
# Entity @s:	 Player
#
give @s emerald{display:{Name:'{"text":"Ruby Gem"}'}}
execute if data storage minuncraft:settings base_item{"diamond":"Enabled"} run give @s diamond{display:{Name:'{"text":"Ruby Gem"}'}}
give @s amethyst_shard{display:{Name:'{"text":"Ruby Gem"}'}}
