#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:55.
#
# Description: Give items with name Strawberry Jam
# Called by:	 Player
# Entity @s:	 Player
#
give @s apple{display:{Name:'{"text":"Strawberry Jam"}'}}
give @s bread{display:{Name:'{"text":"Strawberry Jam"}'}}
