#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:54.
#
# Description: Give items with name Sugar Donut
# Called by:	 Player
# Entity @s:	 Player
#
give @s cookie{display:{Name:'{"text":"Sugar Donut"}'}}
give @s bread{display:{Name:'{"text":"Sugar Donut"}'}}
