#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:54.
#
# Description: Give items with name Yuri Queen Shears
# Called by:	 Player
# Entity @s:	 Player
#
give @s shears{display:{Name:'{"text":"Yuri Queen Shears"}'}}
