#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:58.
#
# Description: Give elytra from table row #33
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:elytra/names/d-ace_lite_b
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:elytra/names/de-ess_exel_b
