#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:58.
#
# Description: Give elytra from table row #41
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:elytra/names/pyra_wings
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:elytra/names/pyra_elytra
execute if score #number_of_names minuncraft matches 3.. run function minuncraft:elytra/names/pyra_scarf_wings
execute if score #number_of_names minuncraft matches 4.. run function minuncraft:elytra/names/pyra_wing_scarf
execute if score #number_of_names minuncraft matches 5.. run function minuncraft:elytra/names/red_aegis_scarf_wings
execute if score #number_of_names minuncraft matches 6.. run function minuncraft:elytra/names/red_aegis_wings
execute if score #number_of_names minuncraft matches 7.. run function minuncraft:elytra/names/red_aegis_elytra
