#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:58.
#
# Description: Give elytra from table row #60
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:elytra/names/transgender_moth_wings
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:elytra/names/transgender_moth_elytra
execute if score #number_of_names minuncraft matches 3.. run function minuncraft:elytra/names/trans_moth_wings
execute if score #number_of_names minuncraft matches 4.. run function minuncraft:elytra/names/trans_moth_elytra
execute if score #number_of_names minuncraft matches 5.. run function minuncraft:elytra/names/trans_elytra
