#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:53.
#
# Description: Give items from table row #14
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:items/names/hypergay_bow_of_the_future
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:items/names/hypergay_future_bow
execute if score #number_of_names minuncraft matches 3.. run function minuncraft:items/names/hypergay_moon_piercer
execute if score #number_of_names minuncraft matches 4.. run function minuncraft:items/names/hypergay_star_striker
execute if score #number_of_names minuncraft matches 5.. run function minuncraft:items/names/hypergay_star_hitter
execute if score #number_of_names minuncraft matches 6.. run function minuncraft:items/names/hypergay_bow_of_kaitlin
execute if score #number_of_names minuncraft matches 7.. run function minuncraft:items/names/hypergay_bow
