#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:54.
#
# Description: Give items from table row #181
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:items/names/iron_knife
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:items/names/survival_knife
