#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:54.
#
# Description: Give items from table row #364
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:items/names/strawberry_doughnut
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:items/names/strawberry_donut
execute if score #number_of_names minuncraft matches 3.. run function minuncraft:items/names/strawberry_iced_doughnut
execute if score #number_of_names minuncraft matches 4.. run function minuncraft:items/names/strawberry_iced_donut
execute if score #number_of_names minuncraft matches 5.. run function minuncraft:items/names/strawberry_glazed_doughnut
execute if score #number_of_names minuncraft matches 6.. run function minuncraft:items/names/strawberry_glazed_donut
