#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:55.
#
# Description: Give items from table row #456
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:items/names/hdd_supreme_axe
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:items/names/hdd_white_supreme_axe
execute if score #number_of_names minuncraft matches 3.. run function minuncraft:items/names/white_supreme_axe
