#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:55.
#
# Description: Give items from table row #503
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:items/names/doughnut_holer
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:items/names/donut_holer
execute if score #number_of_names minuncraft matches 3.. run function minuncraft:items/names/iron_pipe
execute if score #number_of_names minuncraft matches 4.. run function minuncraft:items/names/pipe
execute if score #number_of_names minuncraft matches 5.. run function minuncraft:items/names/rusty_pipe
execute if score #number_of_names minuncraft matches 6.. run function minuncraft:items/names/old_pipe
