#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:55.
#
# Description: Give items from table row #535
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:items/names/garnet_gauntlet_old
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:items/names/season_one_garnet_gauntlet
execute if score #number_of_names minuncraft matches 3.. run function minuncraft:items/names/s1_garnet_gauntlet
