#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:55.
#
# Description: Give items from table row #665
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:items/names/a_kiss_and_a_white_lily
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:items/names/a_kiss_and_a_white_lily_full_collection
execute if score #number_of_names minuncraft matches 3.. run function minuncraft:items/names/a_kiss_and_a_white_lily_complete_collection
