#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:55.
#
# Description: Give items from table row #676
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:items/names/swapswap_volume_1
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:items/names/swapswap_volume_2
execute if score #number_of_names minuncraft matches 3.. run function minuncraft:items/names/swapswap_volume_3
execute if score #number_of_names minuncraft matches 4.. run function minuncraft:items/names/swapswap_volume_4
execute if score #number_of_names minuncraft matches 5.. run function minuncraft:items/names/swap_swap_volume_1
execute if score #number_of_names minuncraft matches 6.. run function minuncraft:items/names/swap_swap_volume_2
execute if score #number_of_names minuncraft matches 7.. run function minuncraft:items/names/swap_swap_volume_3
execute if score #number_of_names minuncraft matches 8.. run function minuncraft:items/names/swap_swap_volume_4
