#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:55.
#
# Description: Give items from table row #679
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:items/names/the_proposal
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:items/names/the_proposal_full_collection
execute if score #number_of_names minuncraft matches 3.. run function minuncraft:items/names/the_proposal_complete_collection
