#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:55.
#
# Description: Give items from table row #682
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:items/names/green_axolotl
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:items/names/gfp_axolotl
execute if score #number_of_names minuncraft matches 3.. run function minuncraft:items/names/spinach
execute if score #number_of_names minuncraft matches 4.. run function minuncraft:items/names/avocado
execute if score #number_of_names minuncraft matches 5.. run function minuncraft:items/names/midori
execute if score #number_of_names minuncraft matches 6.. run function minuncraft:items/names/jade
execute if score #number_of_names minuncraft matches 7.. run function minuncraft:items/names/grass
execute if score #number_of_names minuncraft matches 8.. run function minuncraft:items/names/seaweed
execute if score #number_of_names minuncraft matches 9.. run function minuncraft:items/names/alien
execute if score #number_of_names minuncraft matches 10.. run function minuncraft:items/names/mint
execute if score #number_of_names minuncraft matches 11.. run function minuncraft:items/names/cucumber
execute if score #number_of_names minuncraft matches 12.. run function minuncraft:items/names/pickle
execute if score #number_of_names minuncraft matches 13.. run function minuncraft:items/names/pickles
execute if score #number_of_names minuncraft matches 14.. run function minuncraft:items/names/lime
execute if score #number_of_names minuncraft matches 15.. run function minuncraft:items/names/sargent_spinach
execute if score #number_of_names minuncraft matches 16.. run function minuncraft:items/names/sargent_avocado
execute if score #number_of_names minuncraft matches 17.. run function minuncraft:items/names/sargent_pickle
execute if score #number_of_names minuncraft matches 18.. run function minuncraft:items/names/sargent_lime
