#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:55.
#
# Description: Give items from table row #691
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:items/names/nintendo_switch
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:items/names/switch
execute if score #number_of_names minuncraft matches 3.. run function minuncraft:items/names/blue-red_nintendo_switch
execute if score #number_of_names minuncraft matches 4.. run function minuncraft:items/names/blue-red_switch
execute if score #number_of_names minuncraft matches 5.. run function minuncraft:items/names/neon_blue_and_neon_red_switch
