#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:55.
#
# Description: Give items from table row #706
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:items/names/yellow_nintendo_switch
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:items/names/yellow_switch
execute if score #number_of_names minuncraft matches 3.. run function minuncraft:items/names/neon_yellow_nintendo_switch
execute if score #number_of_names minuncraft matches 4.. run function minuncraft:items/names/neon_yellow_switch
