#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:56.
#
# Description: Give items from table row #769
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:items/names/pencil
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:items/names/graphite_pencil
execute if score #number_of_names minuncraft matches 3.. run function minuncraft:items/names/lead_pencil
execute if score #number_of_names minuncraft matches 4.. run function minuncraft:items/names/6b_pencil
execute if score #number_of_names minuncraft matches 5.. run function minuncraft:items/names/4b_pencil
execute if score #number_of_names minuncraft matches 6.. run function minuncraft:items/names/2b_pencil
execute if score #number_of_names minuncraft matches 7.. run function minuncraft:items/names/hb_pencil
execute if score #number_of_names minuncraft matches 8.. run function minuncraft:items/names/f_pencil
execute if score #number_of_names minuncraft matches 9.. run function minuncraft:items/names/h_pencil
execute if score #number_of_names minuncraft matches 10.. run function minuncraft:items/names/2h_pencil
execute if score #number_of_names minuncraft matches 11.. run function minuncraft:items/names/4h_pencil
