#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:56.
#
# Description: Give items from table row #814
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:items/names/harmonious_harpbow
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:items/names/melodious_harpbow
execute if score #number_of_names minuncraft matches 3.. run function minuncraft:items/names/pink_harpbow
execute if score #number_of_names minuncraft matches 4.. run function minuncraft:items/names/harpbow
execute if score #number_of_names minuncraft matches 5.. run function minuncraft:items/names/harp_bow
