#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:56.
#
# Description: Give items from table row #835
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:items/names/beam_pickaxe
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:items/names/nep_beam_pickaxe
execute if score #number_of_names minuncraft matches 3.. run function minuncraft:items/names/beam_pickaxe_mk3
execute if score #number_of_names minuncraft matches 4.. run function minuncraft:items/names/nep_beam_pickaxe_mk3
