#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:57.
#
# Description: Give armour with name Black Striped Knee High Socks
# Called by:	 Player
# Entity @s:	 Player
#
execute if data storage minuncraft:settings base_item{"leather":"Enabled"} run give @s leather_leggings{display:{Name:'{"text":"Black Striped Knee High Socks"}'}}
