#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:57.
#
# Description: Give armour with name DX Silver W
# Called by:	 Player
# Entity @s:	 Player
#
execute if data storage minuncraft:settings base_item{"diamond":"Enabled"} run give @s diamond_leggings{display:{Name:'{"text":"DX Silver W"}'}}
execute if data storage minuncraft:settings base_item{"netherite":"Enabled"} run give @s netherite_leggings{display:{Name:'{"text":"DX Silver W"}'}}
