#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:57.
#
# Description: Give armour with name Pumpkin Boots
# Called by:	 Player
# Entity @s:	 Player
#
execute if data storage minuncraft:settings base_item{"leather":"Enabled"} run give @s leather_boots{display:{Name:'{"text":"Pumpkin Boots"}'}}
execute if data storage minuncraft:settings base_item{"iron":"Enabled"} run give @s iron_boots{display:{Name:'{"text":"Pumpkin Boots"}'}}
execute if data storage minuncraft:settings base_item{"diamond":"Enabled"} run give @s diamond_boots{display:{Name:'{"text":"Pumpkin Boots"}'}}
execute if data storage minuncraft:settings base_item{"netherite":"Enabled"} run give @s netherite_boots{display:{Name:'{"text":"Pumpkin Boots"}'}}
