#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:57.
#
# Description: Give armour from table row #182
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:armour/names/orion_type_ii_chestplate
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:armour/names/orion_type_ii_breastplate
execute if score #number_of_names minuncraft matches 3.. run function minuncraft:armour/names/rex_chest
execute if score #number_of_names minuncraft matches 4.. run function minuncraft:armour/names/asura_plate
execute if score #number_of_names minuncraft matches 5.. run function minuncraft:armour/names/orion_type_ii_melia_chestplate
execute if score #number_of_names minuncraft matches 6.. run function minuncraft:armour/names/orion_type_ii_melia_breastplate
