#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:57.
#
# Description: Give armour from table row #37
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:armour/names/hypergay_goddess_thighhighs
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:armour/names/hypergay_thighhighs
execute if score #number_of_names minuncraft matches 3.. run function minuncraft:armour/names/hypergay_goddess_socks
execute if score #number_of_names minuncraft matches 4.. run function minuncraft:armour/names/hypergay_kaitlin_thighhighs
execute if score #number_of_names minuncraft matches 5.. run function minuncraft:armour/names/hypergay_thighhighs_of_kaitlin
execute if score #number_of_names minuncraft matches 6.. run function minuncraft:armour/names/hypergay_leggings
