#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:57.
#
# Description: Give armour from table row #58
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:armour/names/cyan_calamity_skirt
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:armour/names/cyan_calamity_leggings
execute if score #number_of_names minuncraft matches 3.. run function minuncraft:armour/names/blue_calamity_skirt
execute if score #number_of_names minuncraft matches 4.. run function minuncraft:armour/names/blue_calamity_leggings
