#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:57.
#
# Description: Give armour from table row #61
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:armour/names/green_calamity_chestplate
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:armour/names/green_calamity_breastplate
