#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:58.
#
# Description: Give all items from all categories to the player
# Called by:	 Player
# Entity @s:	 Player
#
function minuncraft:items/all
function minuncraft:shields/all
function minuncraft:armour/all
function minuncraft:elytra/all
