#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:55.
#
# Description: Give items with name A Kiss and a White Lily Volume 10
# Called by:	 Player
# Entity @s:	 Player
#
give @s book{display:{Name:'{"text":"A Kiss and a White Lily Volume 10"}'}}
