#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:55.
#
# Description: Give items with name About a Fussy Girl's Yuri
# Called by:	 Player
# Entity @s:	 Player
#
give @s book{display:{Name:'{"text":"About a Fussy Girl's Yuri"}'}}
