#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:55.
#
# Description: Give items with name Big Turnip
# Called by:	 Player
# Entity @s:	 Player
#
give @s beetroot{display:{Name:'{"text":"Big Turnip"}'}}
give @s carrot{display:{Name:'{"text":"Big Turnip"}'}}
give @s potato{display:{Name:'{"text":"Big Turnip"}'}}
