#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:55.
#
# Description: Give items with name Bowl of Rice
# Called by:	 Player
# Entity @s:	 Player
#
give @s mushroom_stew{display:{Name:'{"text":"Bowl of Rice"}'}}
