#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:56.
#
# Description: Give items with name Carrot Knife
# Called by:	 Player
# Entity @s:	 Player
#
give @s carrot{display:{Name:'{"text":"Carrot Knife"}'}}
execute if data storage minuncraft:settings base_item{"wood":"Enabled"} run give @s wooden_sword{display:{Name:'{"text":"Carrot Knife"}'}}
