#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:54.
#
# Description: Give items with name Cherry
# Called by:	 Player
# Entity @s:	 Player
#
give @s apple{display:{Name:'{"text":"Cherry"}'}}
give @s sweet_berries{display:{Name:'{"text":"Cherry"}'}}
