#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:54.
#
# Description: Give items with name End Stone Cleaver
# Called by:	 Player
# Entity @s:	 Player
#
execute if data storage minuncraft:settings base_item{"stone":"Enabled"} run give @s stone_sword{display:{Name:'{"text":"End Stone Cleaver"}'}}
