#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:55.
#
# Description: Give items with name Firebolt Thrower
# Called by:	 Player
# Entity @s:	 Player
#
give @s crossbow{display:{Name:'{"text":"Firebolt Thrower"}'}}
