#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:54.
#
# Description: Give items with name Grape Juice
# Called by:	 Player
# Entity @s:	 Player
#
give @s honey_bottle{display:{Name:'{"text":"Grape Juice"}'}}
give @s potion{display:{Name:'{"text":"Grape Juice"}'}}
