#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:56.
#
# Description: Give items with name Green Firework
# Called by:	 Player
# Entity @s:	 Player
#
give @s firework_rocket{display:{Name:'{"text":"Green Firework"}'}}
