#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:56.
#
# Description: Give items with name Grumm
# Called by:	 Player
# Entity @s:	 Player
#
give @s name_tag{display:{Name:'{"text":"Grumm"}'}}
