#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:55.
#
# Description: Give items with name HDD Lilac Gunblade Revised
# Called by:	 Player
# Entity @s:	 Player
#
give @s bow{display:{Name:'{"text":"HDD Lilac Gunblade Revised"}'}}
