#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:56.
#
# Description: Give items with name Invisible Item Frame
# Called by:	 Player
# Entity @s:	 Player
#
give @s item_frame{display:{Name:'{"text":"Invisible Item Frame"}'}}
