#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:55.
#
# Description: Give items with name Jelly-Filled Donut
# Called by:	 Player
# Entity @s:	 Player
#
give @s bread{display:{Name:'{"text":"Jelly-Filled Donut"}'}}
