#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:55.
#
# Description: Give items with name Matcha Pocky
# Called by:	 Player
# Entity @s:	 Player
#
give @s cookie{display:{Name:'{"text":"Matcha Pocky"}'}}
give @s dried_kelp{display:{Name:'{"text":"Matcha Pocky"}'}}
