#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:54.
#
# Description: Give items with name Muesli Bar
# Called by:	 Player
# Entity @s:	 Player
#
give @s baked_potato{display:{Name:'{"text":"Muesli Bar"}'}}
give @s bread{display:{Name:'{"text":"Muesli Bar"}'}}
