#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:54.
#
# Description: Give items with name Netherite Bardiche
# Called by:	 Player
# Entity @s:	 Player
#
execute if data storage minuncraft:settings base_item{"netherite":"Enabled"} run give @s netherite_axe{display:{Name:'{"text":"Netherite Bardiche"}'}}
