#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:54.
#
# Description: Give items with name Notch Banana
# Called by:	 Player
# Entity @s:	 Player
#
give @s enchanted_golden_apple{display:{Name:'{"text":"Notch Banana"}'}}
