#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:56.
#
# Description: Give items with name Pink Bar of Soap
# Called by:	 Player
# Entity @s:	 Player
#
give @s honeycomb{display:{Name:'{"text":"Pink Bar of Soap"}'}}
give @s pink_dye{display:{Name:'{"text":"Pink Bar of Soap"}'}}
