#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:55.
#
# Description: Give items with name Reinforced Fishing Pole
# Called by:	 Player
# Entity @s:	 Player
#
give @s fishing_rod{display:{Name:'{"text":"Reinforced Fishing Pole"}'}}
