#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:56.
#
# Description: Give items with name Reinforced Shears
# Called by:	 Player
# Entity @s:	 Player
#
give @s shears{display:{Name:'{"text":"Reinforced Shears"}'}}
