#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:56.
#
# Description: Give items with name Silver Ring
# Called by:	 Player
# Entity @s:	 Player
#
execute if data storage minuncraft:settings base_item{"iron":"Enabled"} run give @s iron_nugget{display:{Name:'{"text":"Silver Ring"}'}}
execute if data storage minuncraft:settings base_item{"iron":"Enabled"} run give @s iron_ingot{display:{Name:'{"text":"Silver Ring"}'}}
