#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:55.
#
# Description: Give items with name Skyfringe Pickaxe
# Called by:	 Player
# Entity @s:	 Player
#
execute if data storage minuncraft:settings base_item{"iron":"Enabled"} run give @s iron_pickaxe{display:{Name:'{"text":"Skyfringe Pickaxe"}'}}
execute if data storage minuncraft:settings base_item{"diamond":"Enabled"} run give @s diamond_pickaxe{display:{Name:'{"text":"Skyfringe Pickaxe"}'}}
