#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:55.
#
# Description: Give items with name Skyroot Pickaxe
# Called by:	 Player
# Entity @s:	 Player
#
execute if data storage minuncraft:settings base_item{"wood":"Enabled"} run give @s wooden_pickaxe{display:{Name:'{"text":"Skyroot Pickaxe"}'}}
