#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:56.
#
# Description: Give items with name Speed Fragment
# Called by:	 Player
# Entity @s:	 Player
#
give @s cyan_dye{display:{Name:'{"text":"Speed Fragment"}'}}
give @s emerald{display:{Name:'{"text":"Speed Fragment"}'}}
