#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:55.
#
# Description: Give items with name Spool of Pink Thread
# Called by:	 Player
# Entity @s:	 Player
#
give @s string{display:{Name:'{"text":"Spool of Pink Thread"}'}}
