#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:56.
#
# Description: Give items with name Stoneshade Pickaxe
# Called by:	 Player
# Entity @s:	 Player
#
execute if data storage minuncraft:settings base_item{"stone":"Enabled"} run give @s stone_pickaxe{display:{Name:'{"text":"Stoneshade Pickaxe"}'}}
