#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:54.
#
# Description: Give items with name Voidic Mirror
# Called by:	 Player
# Entity @s:	 Player
#
execute if data storage minuncraft:settings base_item{"iron":"Enabled"} run give @s iron_ingot{display:{Name:'{"text":"Voidic Mirror"}'}}
execute if data storage minuncraft:settings base_item{"iron":"Enabled"} run give @s iron_nugget{display:{Name:'{"text":"Voidic Mirror"}'}}
give @s stick{display:{Name:'{"text":"Voidic Mirror"}'}}
