#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:54.
#
# Description: Give items with name Yurilily Queen Pickaxe
# Called by:	 Player
# Entity @s:	 Player
#
execute if data storage minuncraft:settings base_item{"gold":"Enabled"} run give @s golden_pickaxe{display:{Name:'{"text":"Yurilily Queen Pickaxe"}'}}
execute if data storage minuncraft:settings base_item{"iron":"Enabled"} run give @s iron_pickaxe{display:{Name:'{"text":"Yurilily Queen Pickaxe"}'}}
execute if data storage minuncraft:settings base_item{"diamond":"Enabled"} run give @s diamond_pickaxe{display:{Name:'{"text":"Yurilily Queen Pickaxe"}'}}
execute if data storage minuncraft:settings base_item{"netherite":"Enabled"} run give @s netherite_pickaxe{display:{Name:'{"text":"Yurilily Queen Pickaxe"}'}}
