#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:54.
#
# Description: Give items with name Zistonian Battlesign
# Called by:	 Player
# Entity @s:	 Player
#
give @s oak_sign{display:{Name:'{"text":"Zistonian Battlesign"}'}}
