#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:57.
#
# Description: Give armour with name Hardened Leather Chestplate
# Called by:	 Player
# Entity @s:	 Player
#
execute if data storage minuncraft:settings base_item{"leather":"Enabled"} run give @s leather_chestplate{display:{Name:'{"text":"Hardened Leather Chestplate"}'}}
