#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:57.
#
# Description: Give armour with name Lilac mk3 S
# Called by:	 Player
# Entity @s:	 Player
#
execute if data storage minuncraft:settings base_item{"diamond":"Enabled"} run give @s diamond_chestplate{display:{Name:'{"text":"Lilac mk3 S"}'}}
execute if data storage minuncraft:settings base_item{"netherite":"Enabled"} run give @s netherite_chestplate{display:{Name:'{"text":"Lilac mk3 S"}'}}
