#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:58.
#
# Description: Activate the function according to the player's elytra_row score
# Called by:	 minuncraft:second
# Entity @s:	 Player
#
execute if score @s elytra_row matches 2 run function minuncraft:elytra/rows/2
execute if score @s elytra_row matches 3 run function minuncraft:elytra/rows/3
execute if score @s elytra_row matches 4 run function minuncraft:elytra/rows/4
execute if score @s elytra_row matches 5 run function minuncraft:elytra/rows/5
execute if score @s elytra_row matches 6 run function minuncraft:elytra/rows/6
execute if score @s elytra_row matches 7 run function minuncraft:elytra/rows/7
execute if score @s elytra_row matches 8 run function minuncraft:elytra/rows/8
execute if score @s elytra_row matches 9 run function minuncraft:elytra/rows/9
execute if score @s elytra_row matches 10 run function minuncraft:elytra/rows/10
execute if score @s elytra_row matches 11 run function minuncraft:elytra/rows/11
execute if score @s elytra_row matches 12 run function minuncraft:elytra/rows/12
execute if score @s elytra_row matches 13 run function minuncraft:elytra/rows/13
execute if score @s elytra_row matches 14 run function minuncraft:elytra/rows/14
execute if score @s elytra_row matches 15 run function minuncraft:elytra/rows/15
execute if score @s elytra_row matches 16 run function minuncraft:elytra/rows/16
execute if score @s elytra_row matches 17 run function minuncraft:elytra/rows/17
execute if score @s elytra_row matches 18 run function minuncraft:elytra/rows/18
execute if score @s elytra_row matches 19 run function minuncraft:elytra/rows/19
execute if score @s elytra_row matches 20 run function minuncraft:elytra/rows/20
execute if score @s elytra_row matches 21 run function minuncraft:elytra/rows/21
execute if score @s elytra_row matches 22 run function minuncraft:elytra/rows/22
execute if score @s elytra_row matches 23 run function minuncraft:elytra/rows/23
execute if score @s elytra_row matches 24 run function minuncraft:elytra/rows/24
execute if score @s elytra_row matches 25 run function minuncraft:elytra/rows/25
execute if score @s elytra_row matches 26 run function minuncraft:elytra/rows/26
execute if score @s elytra_row matches 27 run function minuncraft:elytra/rows/27
execute if score @s elytra_row matches 28 run function minuncraft:elytra/rows/28
execute if score @s elytra_row matches 29 run function minuncraft:elytra/rows/29
execute if score @s elytra_row matches 30 run function minuncraft:elytra/rows/30
execute if score @s elytra_row matches 31 run function minuncraft:elytra/rows/31
execute if score @s elytra_row matches 32 run function minuncraft:elytra/rows/32
execute if score @s elytra_row matches 33 run function minuncraft:elytra/rows/33
execute if score @s elytra_row matches 34 run function minuncraft:elytra/rows/34
execute if score @s elytra_row matches 35 run function minuncraft:elytra/rows/35
execute if score @s elytra_row matches 36 run function minuncraft:elytra/rows/36
execute if score @s elytra_row matches 37 run function minuncraft:elytra/rows/37
execute if score @s elytra_row matches 38 run function minuncraft:elytra/rows/38
execute if score @s elytra_row matches 39 run function minuncraft:elytra/rows/39
execute if score @s elytra_row matches 40 run function minuncraft:elytra/rows/40
execute if score @s elytra_row matches 41 run function minuncraft:elytra/rows/41
execute if score @s elytra_row matches 42 run function minuncraft:elytra/rows/42
execute if score @s elytra_row matches 43 run function minuncraft:elytra/rows/43
execute if score @s elytra_row matches 44 run function minuncraft:elytra/rows/44
execute if score @s elytra_row matches 45 run function minuncraft:elytra/rows/45
execute if score @s elytra_row matches 46 run function minuncraft:elytra/rows/46
execute if score @s elytra_row matches 47 run function minuncraft:elytra/rows/47
execute if score @s elytra_row matches 48 run function minuncraft:elytra/rows/48
execute if score @s elytra_row matches 49 run function minuncraft:elytra/rows/49
execute if score @s elytra_row matches 50 run function minuncraft:elytra/rows/50
execute if score @s elytra_row matches 51 run function minuncraft:elytra/rows/51
execute if score @s elytra_row matches 52 run function minuncraft:elytra/rows/52
execute if score @s elytra_row matches 53 run function minuncraft:elytra/rows/53
execute if score @s elytra_row matches 54 run function minuncraft:elytra/rows/54
execute if score @s elytra_row matches 55 run function minuncraft:elytra/rows/55
execute if score @s elytra_row matches 56 run function minuncraft:elytra/rows/56
execute if score @s elytra_row matches 57 run function minuncraft:elytra/rows/57
execute if score @s elytra_row matches 58 run function minuncraft:elytra/rows/58
execute if score @s elytra_row matches 59 run function minuncraft:elytra/rows/59
execute if score @s elytra_row matches 60 run function minuncraft:elytra/rows/60
#
# Reset player's trigger score and re-enable
#
scoreboard players set @s elytra_row 0
scoreboard players enable @s elytra_row
