#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:58.
#
# Description: Give elytra with name Manmade Wings
# Called by:	 Player
# Entity @s:	 Player
#
give @s elytra{display:{Name:'{"text":"Manmade Wings"}'}}
