#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:56.
#
# Description: Give shields from table row #20
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:shields/names/belarus_flag_shield
