#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:57.
#
# Description: Give shields from table row #232
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:shields/names/hong_kong_black_bauhinia_flag_shield
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:shields/names/hk_black_bauhinia
execute if score #number_of_names minuncraft matches 3.. run function minuncraft:shields/names/black_bauhinia_flag_shield
