#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:56.
#
# Description: Give shields from table row #46
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:shields/names/czech_republic_flag_shield
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:shields/names/czechia_flag_shield
