#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:56.
#
# Description: Give shields from table row #52
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:shields/names/east_timor_flag_shield
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:shields/names/timor-leste_flag_shield
