#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:57.
#
# Description: Give armour from table row #178
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:armour/names/orion_chestplate
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:armour/names/orion_breastplate
execute if score #number_of_names minuncraft matches 3.. run function minuncraft:armour/names/orion_top
execute if score #number_of_names minuncraft matches 4.. run function minuncraft:armour/names/orion_melia_chestplate
execute if score #number_of_names minuncraft matches 5.. run function minuncraft:armour/names/orion_melia_breastplate
execute if score #number_of_names minuncraft matches 6.. run function minuncraft:armour/names/orion_melia_top
