#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:57.
#
# Description: Give armour from table row #181
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:armour/names/orion_type_ii_boots
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:armour/names/rex_greaves
execute if score #number_of_names minuncraft matches 3.. run function minuncraft:armour/names/asura_greaves
execute if score #number_of_names minuncraft matches 4.. run function minuncraft:armour/names/orion_type_ii_melia_boots
execute if score #number_of_names minuncraft matches 5.. run function minuncraft:armour/names/rex_melia_greaves
execute if score #number_of_names minuncraft matches 6.. run function minuncraft:armour/names/asura_melia_greaves
