#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:57.
#
# Description: Give armour from table row #199
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:armour/names/yurilily_queen_crown
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:armour/names/yuri_queen_crown
execute if score #number_of_names minuncraft matches 3.. run function minuncraft:armour/names/yurilily_crown
execute if score #number_of_names minuncraft matches 4.. run function minuncraft:armour/names/crown_of_the_queendom_of_yurilily
