#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:57.
#
# Description: Give armour from table row #34
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:armour/names/heartplate_leggings
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:armour/names/pinkmetal_leggings
execute if score #number_of_names minuncraft matches 3.. run function minuncraft:armour/names/heart_leggings
execute if score #number_of_names minuncraft matches 4.. run function minuncraft:armour/names/heartsteel_leggings
