#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:58.
#
# Description: Give elytra with name Minecon 2012 Elytra
# Called by:	 Player
# Entity @s:	 Player
#
give @s elytra{display:{Name:'{"text":"Minecon 2012 Elytra"}'}}
