#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:58.
#
# Description: Give elytra from table row #45
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:elytra/names/minecon_2015_elytra
