#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:58.
#
# Description: Give elytra from table row #56
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:elytra/names/manmade_elytra
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:elytra/names/manmade_wings
execute if score #number_of_names minuncraft matches 3.. run function minuncraft:elytra/names/man-made_elytra
execute if score #number_of_names minuncraft matches 4.. run function minuncraft:elytra/names/man-made_wings
execute if score #number_of_names minuncraft matches 5.. run function minuncraft:elytra/names/makeshift_wings
