#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:58.
#
# Description: Give all items from this category to the player
# Called by:	 Player
# Entity @s:	 Player
#
function minuncraft:elytra/rows/2
function minuncraft:elytra/rows/3
function minuncraft:elytra/rows/4
function minuncraft:elytra/rows/5
function minuncraft:elytra/rows/6
function minuncraft:elytra/rows/7
function minuncraft:elytra/rows/8
function minuncraft:elytra/rows/9
function minuncraft:elytra/rows/10
function minuncraft:elytra/rows/11
function minuncraft:elytra/rows/12
function minuncraft:elytra/rows/13
function minuncraft:elytra/rows/14
function minuncraft:elytra/rows/15
function minuncraft:elytra/rows/16
function minuncraft:elytra/rows/17
function minuncraft:elytra/rows/18
function minuncraft:elytra/rows/19
function minuncraft:elytra/rows/20
function minuncraft:elytra/rows/21
function minuncraft:elytra/rows/22
function minuncraft:elytra/rows/23
function minuncraft:elytra/rows/24
function minuncraft:elytra/rows/25
function minuncraft:elytra/rows/26
function minuncraft:elytra/rows/27
function minuncraft:elytra/rows/28
function minuncraft:elytra/rows/29
function minuncraft:elytra/rows/30
function minuncraft:elytra/rows/31
function minuncraft:elytra/rows/32
function minuncraft:elytra/rows/33
function minuncraft:elytra/rows/34
function minuncraft:elytra/rows/35
function minuncraft:elytra/rows/36
function minuncraft:elytra/rows/37
function minuncraft:elytra/rows/38
function minuncraft:elytra/rows/39
function minuncraft:elytra/rows/40
function minuncraft:elytra/rows/41
function minuncraft:elytra/rows/42
function minuncraft:elytra/rows/43
function minuncraft:elytra/rows/44
function minuncraft:elytra/rows/45
function minuncraft:elytra/rows/46
function minuncraft:elytra/rows/47
function minuncraft:elytra/rows/48
function minuncraft:elytra/rows/49
function minuncraft:elytra/rows/50
function minuncraft:elytra/rows/51
function minuncraft:elytra/rows/52
function minuncraft:elytra/rows/53
function minuncraft:elytra/rows/54
function minuncraft:elytra/rows/55
function minuncraft:elytra/rows/56
function minuncraft:elytra/rows/57
function minuncraft:elytra/rows/58
function minuncraft:elytra/rows/59
function minuncraft:elytra/rows/60
