#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:57.
#
# Description: Give shields from table row #131
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:shields/names/north_macedonia_flag_shield
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:shields/names/fyr_macedonia_flag_shield
execute if score #number_of_names minuncraft matches 3.. run function minuncraft:shields/names/macedonia_flag_shield
execute if score #number_of_names minuncraft matches 4.. run function minuncraft:shields/names/fyrom_flag_shield
