#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:57.
#
# Description: Give shields from table row #193
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:shields/names/uk_flag_shield
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:shields/names/united_kingdom_flag_shield
execute if score #number_of_names minuncraft matches 3.. run function minuncraft:shields/names/union_jack_shield
execute if score #number_of_names minuncraft matches 4.. run function minuncraft:shields/names/union_jack_flag_shield
