#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:57.
#
# Description: Give shields from table row #237
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:shields/names/non-binary_pride_flag_shield
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:shields/names/non-binary_pride_shield
execute if score #number_of_names minuncraft matches 3.. run function minuncraft:shields/names/non-binary_flag_shield
execute if score #number_of_names minuncraft matches 4.. run function minuncraft:shields/names/nonbinary_pride_flag_shield
execute if score #number_of_names minuncraft matches 5.. run function minuncraft:shields/names/nonbinary_pride_shield
execute if score #number_of_names minuncraft matches 6.. run function minuncraft:shields/names/nonbinary_flag_shield
execute if score #number_of_names minuncraft matches 7.. run function minuncraft:shields/names/enby_pride_flag_shield
execute if score #number_of_names minuncraft matches 8.. run function minuncraft:shields/names/enby_pride_shield
execute if score #number_of_names minuncraft matches 9.. run function minuncraft:shields/names/enby_flag_shield
