#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:57.
#
# Description: Give shields from table row #253
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:shields/names/acacia_wood_buckler
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:shields/names/acacia_buckler
