#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:56.
#
# Description: Give shields from table row #26
# Called by:	 Player
# Entity @s:	 Player
#
execute if score #number_of_names minuncraft matches 1.. run function minuncraft:shields/names/bosnia_and_herzegovina_flag_shield
execute if score #number_of_names minuncraft matches 2.. run function minuncraft:shields/names/bosnia_flag_shield
