#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:56.
#
# Description: Give shields with name Antigua and Barbuda Flag Shield
# Called by:	 Player
# Entity @s:	 Player
#
give @s shield{display:{Name:'{"text":"Antigua and Barbuda Flag Shield"}'}}
