#
# Generated by datapack-generator v.1.0 on 2022-07-21 22:59:57.
#
# Description: Give shields with name Macedonia Flag Shield
# Called by:	 Player
# Entity @s:	 Player
#
give @s shield{display:{Name:'{"text":"Macedonia Flag Shield"}'}}
